<?php

/**
 * PeopleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeopleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PeopleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('People');
    }
}