<?php

/**
 * People
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfDoctrineRestGeneratorPlugin-demo
 * @subpackage model
 * @author     Xavier Lacot <xavier@lacot.org>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class People extends BasePeople
{
}
